### PR TITLE
Initial layout

### PR DESCRIPTION
**Pull request by devjona**
This PR is so that we can add comments, discuss, etc.

### CODE REVIEW

**Comment by devjona** [comment]
@Himynameislou :
# Image issues:
- You're using width, height to try and keep the image centered and in check. Instead, wrap the the image with a `div` that uses bootstrap classes to size and position it how you want. 
- You'll probably find you can get rid of a lot of the stuff in the `#mePic` styles as a result of the changes.

**Comment by devjona** [comment]
## "Web Developer" box issues
 - `<div class="col-4 text-center w-50 box">` There is too much going on in this line
 - the `.col-*` classes are `width: x%` under the hood. Check them out in the inspector. The code makes this box too narrow at smaller screen widths, then you're also overriding it with the `.w-50` class.
 - Try using responsive `col-/sm/md` classes to adapt this as-needed
 - Good use of the `.justify-content-center` class.

**Comment by devjona** [comment]
## Background issues:
- Your background is repeating. [Check this out](https://developer.mozilla.org/en-US/docs/Web/CSS/background) for a fix.

**Comment by Himynameislou** [comment]
> @Himynameislou :
> 
> # Image issues:
> * You're using width, height to try and keep the image centered and in check. Instead, wrap the the image with a `div` that uses bootstrap classes to size and position it how you want.
> * You'll probably find you can get rid of a lot of the stuff in the `#mePic` styles as a result of the changes.

Fixed by adding col div.

**Comment by Himynameislou** [comment]
> ## "Web Developer" box issues
> * `<div class="col-4 text-center w-50 box">` There is too much going on in this line
> * the `.col-*` classes are `width: x%` under the hood. Check them out in the inspector. The code makes this box too narrow at smaller screen widths, then you're also overriding it with the `.w-50` class.
> * Try using responsive `col-/sm/md` classes to adapt this as-needed
> * Good use of the `.justify-content-center` class.

I removed the w-25 box and now the box looks good on mobile

**Comment by Himynameislou** [comment]
> ## Background issues:
> * Your background is repeating. [Check this out](https://developer.mozilla.org/en-US/docs/Web/CSS/background) for a fix.

Fixed the image color lightening on the background but now in dev mode you will notice when sizing for iPhone that the background image now only goes as far down as the furthest div

**Comment by Himynameislou** [comment]
@devjona I've edited the issues to the best of my abilities.  The background is now lighter but it seems to only reside within the current working divs.  To see what I mean, load the site and then size for iPhone.  There is a bunch of whitespace undereath.
Screen Shot 2021-01-17 at 3 52 25 PM

**Comment by Himynameislou** [comment]
@devjona Also, I'd like to make the size of the picture of me and carmela smaller but I haven't been able to find a good solution.

**Pull request closed without merging**
